FROM node:22

# Build arguments
ARG PORT
ARG ADMIN_URL
ARG QRCODE_URL
ARG ONGKIR_URL
ARG GCLOUD_PROJECT
ARG GOOGLE_APPLICATION_CREDENTIALS
ARG GOOGLE_PRIVATE_KEY_ID
ARG GOOGLE_PRIVATE_KEY
ARG GOOGLE_CLIENT_EMAIL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_X509_CERT_URL
ARG TICKET_GMAIL
ARG TICKET_GMAIL_PASSWORD
ARG MERCH_GMAIL
ARG MERCH_GMAIL_PASSWORD
ARG SPREADSHEET_ID
ARG TICKET_SHEET_NAME
ARG TICKET_SHEET_ID
ARG MERCH_SHEET_NAME
ARG MERCH_SHEET_ID
ARG TICKET_PAYMENT_FOLDER_ID
ARG TICKET_FOLLOW_FOLDER_ID
ARG MERCH_PAYMENT_FOLDER_ID
ARG ADMIN_ID
ARG ADMIN_USERNAME
ARG ADMIN_PASSWORD
ARG ACCESS_TOKEN_SECRET_KEY
ARG REFRESH_TOKEN_SECRET_KEY
ARG ONGKIR_API_KEY

# Set environment variables
ENV PORT=$PORT
ENV ADMIN_URL=$ADMIN_URL
ENV QRCODE_URL=$QRCODE_URL
ENV ONGKIR_URL=$ONGKIR_URL
ENV GCLOUD_PROJECT=$GCLOUD_PROJECT
ENV GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
ENV GOOGLE_PRIVATE_KEY_ID=$GOOGLE_PRIVATE_KEY_ID
ENV GOOGLE_PRIVATE_KEY=$GOOGLE_PRIVATE_KEY
ENV GOOGLE_CLIENT_EMAIL=$GOOGLE_CLIENT_EMAIL
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_X509_CERT_URL=$GOOGLE_CLIENT_X509_CERT_URL
ENV TICKET_GMAIL=$TICKET_GMAIL
ENV TICKET_GMAIL_PASSWORD=$TICKET_GMAIL_PASSWORD
ENV MERCH_GMAIL=$MERCH_GMAIL
ENV MERCH_GMAIL_PASSWORD=$MERCH_GMAIL_PASSWORD
ENV SPREADSHEET_ID=$SPREADSHEET_ID
ENV TICKET_SHEET_NAME=$TICKET_SHEET_NAME
ENV MERCH_SHEET_NAME=$MERCH_SHEET_NAME
ENV MERCH_SHEET_ID=$MERCH_SHEET_ID
ENV TICKET_PAYMENT_FOLDER_ID=$TICKET_PAYMENT_FOLDER_ID
ENV TICKET_FOLLOW_FOLDER_ID=$TICKET_FOLLOW_FOLDER_ID
ENV MERCH_PAYMENT_FOLDER_ID=$MERCH_PAYMENT_FOLDER_ID
ENV ADMIN_ID=$ADMIN_ID
ENV ADMIN_USERNAME=$ADMIN_USERNAME
ENV ADMIN_PASSWORD=$ADMIN_PASSWORD
ENV ACCESS_TOKEN_SECRET_KEY=$ACCESS_TOKEN_SECRET_KEY
ENV REFRESH_TOKEN_SECRET_KEY=$REFRESH_TOKEN_SECRET_KEY
ENV ONGKIR_API_KEY=$ONGKIR_API_KEY

COPY . /app

WORKDIR /app

RUN npm install

EXPOSE $PORT

CMD ["npm", "start"]
